export const EBCA_GQL_GATEWAY_OPTIONS = Symbol('EBCA_GQL_GATEWAY_OPTIONS');
export const EBCA_GQL_INBOUND_NORMALIZERS = Symbol(
  'EBCA_GQL_INBOUND_NORMALIZERS',
);
export const EBCA_GQL_PROJECTION_POLICIES = Symbol(
  'EBCA_GQL_PROJECTION_POLICIES',
);
export const EBCA_GQL_AUDIENCE_RESOLVERS = Symbol(
  'EBCA_GQL_AUDIENCE_RESOLVERS',
);
