export const EBCA_ANALYTICS_SINK_OPTIONS = Symbol(
  'EBCA_ANALYTICS_SINK_OPTIONS',
);

export const EBCA_ANALYTICS_SINK_DEFAULT_BATCH_SIZE = 100;
export const EBCA_ANALYTICS_SINK_DEFAULT_FLUSH_INTERVAL_MS = 5_000;
